name: pnpm Cypress Example Workflow
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Run Cypress
      uses: cypress-io/github-action@v4
      with:
        browser: chrome